### ISSUE TITLE
Bot crash

### ISSUE THREAD

**Issue by aidowalnut** [TheSharks/WildBeast#240]
error:  ReqlOpFailedError: Database `Discord` does not exist in:
r.db("Discord").table("Guilds").insert({
^^^^^^^^^^^^^^^
    customize: {
        nsfw: null,
        perms: null,
        prefix: null,
        volume: 25,
        timeout: null,
        welcome: false,
        welcomeMessage: null
    },
    id: "272896244412579841",
    lang: "en",
    perms: {
        roles: {
            level1: [],
            level2: [],
            level3: [],
            negative: []
        },
        standard: {
            everyone: 0,
            level1: [],
            level2: [],
            level3: [],
            negative: []
        },
        nsfw: []
    },
    superUser: "145639018955014154"
})

    at Connection._processResponse (D:\Aidan\Documents\DiscordBots\WildBeast\node_modules\rethinkdbdash\lib\connection.js:395:15)
    at Socket.<anonymous> (D:\Aidan\Documents\DiscordBots\WildBeast\node_modules\rethinkdbdash\lib\connection.js:201:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
^C

This happens whenever a message is entered in chat

**Comment by caf203** [comment]
Did you run npm run-script dbcreate? That is required...
