### ISSUE TITLE
Bugsnag:  TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by cococov** [TheSharks/WildBeast#286]
C:\Users\....\WildBeast>node DougBot.js
Bugsnag:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:695:5)
    at Object.<anonymous> (C:\Users\Juan K\WildBeast\node_modules\youtube-dl\lib\youtube-dl.js:19:71)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Juan K\WildBeast\runtime\internal\voice.js:7:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Juan K\WildBeast\runtime\commands\music.js:2:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at C:\Users\Juan K\WildBeast\node_modules\require-directory\index.js:76:17
    at Array.forEach (native)
    at requireDirectory (C:\Users\Juan K\WildBeast\node_modules\require-directory\index.js:59:24)
    at Object.<anonymous> (C:\Users\Juan K\WildBeast\runtime\commandcontrol.js:6:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at C:\Users\Juan K\WildBeast\node_modules\require-directory\index.js:76:17
    at Array.forEach (native)
    at requireDirectory (C:\Users\Juan K\WildBeast\node_modules\require-directory\index.js:59:24)
    at Object.<anonymous> (C:\Users\Juan K\WildBeast\runtime\runtime.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Juan K\WildBeast\DougBot.js:20:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by LWTechGaming** [comment]
Run `npm rebuild youtube-dl` and try again.
