### ISSUE TITLE
Request command not working [Full error inside]

### ISSUE THREAD

**Issue by wgolyoko** [TheSharks/WildBeast#302]
Hello,

I'm having trouble with the request command.
The bot does join the channel normally, but when I request a song, there it goes :

error:  Error: spawn UNKNOWN
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:369:9)
    at exports.execFile (child_process.js:137:15)
    at call (C:\Users\Moi\Desktop\WildBeast-master\node_modules\youtube-dl\lib\youtube-dl.js:163:5)
    at Function.getInfo (C:\Users\Moi\Desktop\WildBeast-master\node_modules\youtube-dl\lib\youtube-dl.js:285:5)
    at C:\Users\Moi\Desktop\WildBeast-master\runtime\internal\voice.js:525:8
    at fetch (C:\Users\Moi\Desktop\WildBeast-master\runtime\internal\voice.js:513:10)
    at Object.exports.request (C:\Users\Moi\Desktop\WildBeast-master\runtime\internal\voice.js:473:7)
    at Object.fn (C:\Users\Moi\Desktop\WildBeast-master\runtime\commands\music.js:159:9)
    at timeout.check.then.e (C:\Users\Moi\Desktop\WildBeast-master\DougBot.js:145:37)

I can't seem to find the util.js file mentionned.

Is this a known problem ?

**Comment by wgolyoko** [comment]
Okay, resolved by using youtube-dl 1.11.1
