### ISSUE TITLE
Request command not working

### ISSUE THREAD

**Issue by TLNiles** [TheSharks/WildBeast#303]
Okay, so I've seen somewhat similar resolved issue, but even after updating youtube-dl module, error still remains.

```
error:  Error: spawn UNKNOWN
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at exports.execFile (child_process.js:212:15)
    at call (D:\WildBeast bot\WildBeast\node_modules\youtube-dl\lib\youtube-dl.j
s:163:5)
    at Function.getInfo (D:\WildBeast bot\WildBeast\node_modules\youtube-dl\lib\
youtube-dl.js:285:5)
    at D:\WildBeast bot\WildBeast\runtime\internal\voice.js:525:8
    at new Promise (<anonymous>)
    at fetch (D:\WildBeast bot\WildBeast\runtime\internal\voice.js:513:10)
    at Object.exports.request (D:\WildBeast bot\WildBeast\runtime\internal\voice
.js:473:7)
    at Object.fn (D:\WildBeast bot\WildBeast\runtime\commands\music.js:159:9)
    at timeout.check.then.t (D:\WildBeast bot\WildBeast\DougBot.js:146:37)
    at <anonymous>
```

I am not that much of a code guy, so I'm not entirely sure what would be the cause of it.

**Comment by zaza7** [comment]
https://github.com/przemyslawpluta/node-youtube-dl/issues/167

**Comment by TLNiles** [comment]
Checked and performed. As indeed, problem got fixed, thanks.
