### ISSUE TITLE
I get an error in cmd

### ISSUE THREAD

**Issue by lilcheo** [TheSharks/WildBeast#312]
return binding.mkdir(pathModule._makeLong(path),

**Comment by Nenkai** [comment]
Please give more details, which command? Node version? OS..?
Also a full stack trace would help.

**Comment by lilcheo** [comment]
@nenkai OS=Windows 8.1 Node version 8.9.3 and the whole cmd thingy is   return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'G:\my stuff\Discord bot\1\logs\
exceptions.-Fr-02-yyyy.2\2'
    at Object.fs.mkdirSync (fs.js:885:18)
    at G:\my stuff\Discord bot\1\node_modules\file-stream-rotator\FileStreamRota
tor.js:470:20
    at Array.reduce (<anonymous>)
    at mkDirForFile (G:\my stuff\Discord bot\1\node_modules\file-stream-rotator\
FileStreamRotator.js:458:27)
    at Object.FileStreamRotator.getStream (G:\my stuff\Discord bot\1\node_module
s\file-stream-rotator\FileStreamRotator.js:384:5)
    at new DailyRotateFile (G:\my stuff\Discord bot\1\node_modules\winston-daily
-rotate-file\daily-rotate-file.js:67:57)
    at Object.<anonymous> (G:\my stuff\Discord bot\1\runtime\internal\logger.js:
48:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

**Comment by Nenkai** [comment]
Delete the contents of the `logs` folder, see if it persists.

**Comment by lilcheo** [comment]
@nenkai nope still same thing   return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'G:\my stuff\Discord bot\1\logs\
exceptions.-Fr-02-yyyy.2\2'
    at Object.fs.mkdirSync (fs.js:885:18)
    at G:\my stuff\Discord bot\1\node_modules\file-stream-rotator\FileStreamRota
tor.js:470:20
    at Array.reduce (<anonymous>)
    at mkDirForFile (G:\my stuff\Discord bot\1\node_modules\file-stream-rotator\
FileStreamRotator.js:458:27)
    at Object.FileStreamRotator.getStream (G:\my stuff\Discord bot\1\node_module
s\file-stream-rotator\FileStreamRotator.js:384:5)
    at new DailyRotateFile (G:\my stuff\Discord bot\1\node_modules\winston-daily
-rotate-file\daily-rotate-file.js:67:57)
    at Object.<anonymous> (G:\my stuff\Discord bot\1\runtime\internal\logger.js:
48:7)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)

**Comment by Nenkai** [comment]
Could you run `npm i winston@2.4.0` in a prompt and see if anything changes?
If not, i'd suggest redownloading the bot in a different folder, if possible and test again.

**Comment by lilcheo** [comment]
@nenkai still the same i did but still didnt work
