### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by omerbadawy11** [TheSharks/WildBeast#323]
**PS C:\Users\Test\Desktop\Discord\WildBeast> npm install --global --production windows-build-tools**

> windows-build-tools@3.0.0 postinstall C:\Users\Test\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./dist/index.js

Downloading python-2.7.14.amd64.msi
Downloading BuildTools_Full.exe
[>                                            ] 0.0% (0 B/s)
Downloaded BuildTools_Full.exe. Saved to C:\Users\Test\.windows-build-tools\BuildTools_Full.exe.

Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!

Status from the installers:
---------- Visual Studio Build Tools ----------
Successfully installed Visual Studio Build Tools.
------------------- Python --------------------
Successfully installed Python 2.7

All done!

+ windows-build-tools@3.0.0
updated 1 package in 96.225s
**PS C:\Users\Test\Desktop\Discord\WildBeast> npm install**
npm WARN eslint-plugin-react@6.7.1 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

up to date in 53.286s

**Comment by Dougley** [comment]
What exactly is your issue? Based on the traceback you provided, everything completed successfully.

**Comment by omerbadawy11** [comment]
When i do "npn install" i noticed i get 
npm WARN eslint-plugin-react@6.7.1 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

also when i try to run

"npn DougBot.js" i get
Bugsnag:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:715:5)
    at Object.<anonymous> (C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\node_modules\youtube-dl\lib\youtube-dl.js:21:73)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\runtime\internal\voice.js:6:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\runtime\commands\music.js:2:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\node_modules\require-directory\index.js:76:17
    at Array.forEach (<anonymous>)
    at requireDirectory (C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\node_modules\require-directory\index.js:59:24)
    at Object.<anonymous> (C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\runtime\commandcontrol.js:6:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\node_modules\require-directory\index.js:76:17
    at Array.forEach (<anonymous>)
    at requireDirectory (C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\node_modules\require-directory\index.js:59:24)
    at Object.<anonymous> (C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\runtime\runtime.js:3:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Test\Desktop\Pen_Testing\Discord\WildBeast\DougBot.js:20:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by Dougley** [comment]
The npm warning is a non-issue, it's safe to ignore.
`Path must be a string. Received undefined` can be fixed by repairing youtube-dl (`npm rebuild youtube-dl`), please see https://github.com/przemyslawpluta/node-youtube-dl/issues/167 for more info.

**Comment by omerbadawy11** [comment]
solved, thank you!
