### ISSUE TITLE
Dont know what causes this error but...

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#348]
I randomly get this error after WildBeast has been running for a while.
`INFO: Beginning startup sequence...
INFO: Scaling known. Total: 1, mine: 0
INFO: Fully up-to-date, nice!
INFO: Fully ready, serving 497 guild(s).
INFO: LavaLink node ws://192.168.99.100:2333 ready.
WARN: Error: Connection reset by peer
ERROR: [object Object],0
FATAL: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:171:17)
    at Client.emit (C:\Users\j3zza\Desktop\WildBeast\index.js:29:25)
    at Shard.emit (C:\Users\j3zza\Desktop\WildBeast\node_modules\eris\lib\gateway\Shard.js:1888:26)
    at WebSocket.ws.onerror (C:\Users\j3zza\Desktop\WildBeast\node_modules\eris\lib\gateway\Shard.js:1612:18)
    at WebSocket.onError (C:\Users\j3zza\Desktop\WildBeast\node_modules\eris\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (events.js:182:13)
    at ClientRequest.req.on (C:\Users\j3zza\Desktop\WildBeast\node_modules\eris\node_modules\ws\lib\websocket.js:528:10)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wildbeast@6.1.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wildbeast@6.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j3zza\AppData\Roaming\npm-cache\_logs\2018-09-12T02_00_53_798Z-debug.log`

**Comment by Dougley** [comment]
Your websocket to discord broke unexpectedly, wildbeast will treat behavior like this as a fatal error and won't try to recover itself.
