### ISSUE TITLE
Urban Dictionary

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#368]
the urban dictionary command gave this error and crashed WildBeast.
`CMD: urbandictionary by Kulicee in The Afterlife
FATAL: TypeError: Cannot read property 'word' of undefined
    at request.get.query.end (C:\Users\j3zza\Desktop\Zandercraft-Bot\src\commands\urbandictionary.js:26:69)
    at Request.callback (C:\Users\j3zza\Desktop\Zandercraft-Bot\node_modules\superagent\lib\node\index.js:716:12)
    at parser (C:\Users\j3zza\Desktop\Zandercraft-Bot\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.res.on (C:\Users\j3zza\Desktop\Zandercraft-Bot\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1085:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wildbeast@6.1.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wildbeast@6.1.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\j3zza\AppData\Roaming\npm-cache\_logs\2018-09-16T02_27_43_400Z-debug.log`

**Comment by caf203** [comment]
Resolved, closing this issue.

**Comment by Dougley** [comment]
![](https://i.imgur.com/BgoO2B1.png)

**Comment by ZandercraftGames** [comment]
Wow... lol

**Comment by caf203** [comment]
There was a fix in the works, so I closed it. See latest commit.
