### ISSUE TITLE
Shard disconnect not handled properly

### ISSUE THREAD

**Issue by ZandercraftGames** [TheSharks/WildBeast#380]
Someone ran the +settings command, I dont know what suffixes, but it ended up in this fatal error which crashed the process.
`FATAL: TypeError: Cannot read property 'message' of null
    at Object.module.exports [as shardDisconnect] (/opt/wildbeast/src/events/shardDisconnect.js:2:14)
    at Client.bot.onAny (/opt/wildbeast/index.js:43:21)
    at _anyListeners.forEach.listener (/opt/wildbeast/index.js:28:53)
    at Array.forEach (<anonymous>)
    at Client.emit (/opt/wildbeast/index.js:28:24)
    at Shard.shard.on.on.on (/opt/wildbeast/node_modules/eris/lib/gateway/ShardManager.js:97:30)
    at Shard.emit (events.js:182:13)
    at Shard.disconnect (/opt/wildbeast/node_modules/eris/lib/gateway/Shard.js:120:15)
    at ws.onclose (/opt/wildbeast/node_modules/eris/lib/gateway/Shard.js:1653:18)
    at WebSocketClient.internalOnClose (/opt/wildbeast/node_modules/uws/uws.js:121:17)`

**Comment by ZandercraftGames** [comment]
Another error:
`CMD: request by USERNAME in [ P G ] ([ P M ]เก่า)
FATAL: TypeError: Cannot read property 'message' of null
    at Object.module.exports [as shardDisconnect] (/opt/wildbeast/src/events/shardDisconnect.js:2:14)
    at Client.bot.onAny (/opt/wildbeast/index.js:43:21)
    at _anyListeners.forEach.listener (/opt/wildbeast/index.js:28:53)
    at Array.forEach (<anonymous>)
    at Client.emit (/opt/wildbeast/index.js:28:24)
    at Shard.shard.on.on.on (/opt/wildbeast/node_modules/eris/lib/gateway/ShardManager.js:97:30)
    at Shard.emit (events.js:182:13)
    at Shard.disconnect (/opt/wildbeast/node_modules/eris/lib/gateway/Shard.js:120:15)
    at ws.onclose (/opt/wildbeast/node_modules/eris/lib/gateway/Shard.js:1653:18)
    at WebSocketClient.internalOnClose (/opt/wildbeast/node_modules/uws/uws.js:121:17)`

**Comment by ZandercraftGames** [comment]
This is getting annoying... It was fine before... But in the last 3 days it doesnt even stay online for over 15 minutes.

**Comment by linuswillner** [comment]
This is a shard disconnect bug that we are also seeing on the production instance. We are working on a fix.

**Comment by ZandercraftGames** [comment]
@Dougley did that fix it?

**Comment by Dougley** [comment]
> `closes #380`
Oh boy I sure do wonder

**Comment by ZandercraftGames** [comment]
@Dougley Your commit didnt fix it...
`WARN: Discord connection broke, shard disconnected
ERROR: [object Object],0
FATAL: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
    at Client.emit (events.js:171:17)
    at Client.emit (/opt/wildbeast/index.js:29:25)
    at Shard.emit (/opt/wildbeast/node_modules/eris/lib/gateway/Shard.js:1888:26)
    at WebSocketClient.ws.onerror [as internalOnError] (/opt/wildbeast/node_modules/eris/lib/gateway/Shard.js:1612:18)
    at process.nextTick (/opt/wildbeast/node_modules/uws/uws.js:80:19)
    at process._tickCallback (internal/process/next_tick.js:61:11)`

**Comment by Dougley** [comment]
At this point just restart...    
We can't handle every error, the fact that this was logged by the logger for `uncaughtException` is already rare.

**Comment by Dougley** [comment]
Additionally, you've reported this error before https://github.com/TheSharks/WildBeast/issues/348
