### ISSUE TITLE
Urban Dictionary crash bug

### ISSUE THREAD

**Issue by cryptotoad** [TheSharks/WildBeast#526]
**Describe the bug**
Words not in urban dictionary crash the bot

**To Reproduce**
?ud citanul

**Expected behavior**
An error message

**Additional context**
urbandictionary.js line 22
replace the || with &&
`if (uD.result_type !== 'no_results' && uD.list.length > 0) {`

**Comment by linuswillner** [comment]
What’s the error message you’re getting here?

**Comment by cryptotoad** [comment]
```
FATAL: TypeError: Cannot read property 'word' of undefined
    at request.get.query.end (/opt/wildbeast/src/commands/urbandictionary.js:27:69)
    at Request.callback (/opt/wildbeast/node_modules/superagent/lib/node/index.js:873:12)
    at /opt/wildbeast/node_modules/superagent/lib/node/index.js:1105:20
    at IncomingMessage.<anonymous> (/opt/wildbeast/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by linuswillner** [comment]
Seems to definitely be a problem. Thanks for the report, we’ll fix it ASAP.
