### ISSUE TITLE
 SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by BRAVO68WEB** [TheSharks/WildBeast#659]
I freshly created a bot and having this error every time start the bot. Please assist ...

```
ERROR:NODE] - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at module.exports (/home/kalibravo68/Bot_Instance_1/WildBeast/src/events/ready.js:37:47)
    at /home/kalibravo68/Bot_Instance_1/WildBeast/src/components/client.js:51:51
    at Array.forEach (<anonymous>)
    at Client.<anonymous> (/home/kalibravo68/Bot_Instance_1/WildBeast/src/components/client.js:51:38)
    at /home/kalibravo68/Bot_Instance_1/WildBeast/src/components/client.js:30:51
    at Array.forEach (<anonymous>)
    at Client.emit (/home/kalibravo68/Bot_Instance_1/WildBeast/src/components/client.js:30:22)
    at Shard.<anonymous> (/home/kalibravo68/Bot_Instance_1/WildBeast/node_modules/eris/lib/gateway/ShardManager.js:71:30)
    at Shard.emit (/home/kalibravo68/Bot_Instance_1/WildBeast/node_modules/eventemitter3/index.js:180:35)
```

**Comment by Dougley** [comment]
v7 relies on Lavalink being present in the configuration in order to run music streaming related commands. If you have a Lavalink server running on your machine/network, add it to your `.env` file under `LAVALINK_NODES`, for example:

```env
# This is an example, this will probably not work with your setup without some editing 
LAVALINK_NODES=[{"host": "localhost", "password": "hunter2", "port": 8080, "region": "eu"}]
```

If you don't want to use Lavalink and therefor disable streaming related commands, set `LAVALINK_NODES` to `[]`

```env
LAVALINK_NODES=[]
```

**Comment by BRAVO68WEB** [comment]
Thank you @Dougley that works!!
